-- DV049: Add FRIDGE to KITCHEN and WET_KITCHEN MEP BOM schedules
-- Implementing S157 Priority 3c — Witness: W-FRIDGE-SCHEDULE
--
-- FRIDGE was seeded in M_Product_Image (DV043/CL_001) with raw geometry hash
-- but never added to ad_space_type_mep_bom → never generated by MEP walker.
-- SINK is already in KITCHEN schedule; FRIDGE is the missing product.
--
-- Idempotent: INSERT OR IGNORE — safe to re-run.
-- Target DB: component_library.db

INSERT OR IGNORE INTO ad_space_type_mep_bom
    (space_type_id, mep_product_id, qty_min, qty_normal, qty_max,
     placement_rule, host_surface)
VALUES
    ('KITCHEN',     'FRIDGE', 0, 1, 1, 'AUTO', 'WALL'),
    ('WET_KITCHEN', 'FRIDGE', 0, 1, 1, 'AUTO', 'WALL');
