package com.bim.designer.api;

/**
 * A proposed C_OrderLine generated by an {@link OrderLineMutation}.
 *
 * <p>Represents a rule-driven MEP product suggestion for a room.
 * Not yet persisted — the caller decides whether to insert as PROPOSED.
 *
 * <p>// Implementing ProjectOrderBlueprint.md §14.3 Session B — Witness: W-DM-FP-VAL-1
 */
public record ProposedOrderLine(
        int parentRoomLineId,
        String roomCategory,
        String mepProductId,
        String discipline,
        int qty,
        String placementRule,
        String buildingCode,
        String codeClause
) {}
