package com.bim.compiler.dsl;

import com.bim.compiler.util.OutlierLogger;
import java.nio.file.*;

/**
 * TB-LKTN Verification - Scrutinize compilation results
 */
public class TBLKTNVerify {

    public static void main(String[] args) throws Exception {
        System.out.println("=".repeat(70));
        System.out.println("TB-LKTN VERIFICATION");
        System.out.println("=".repeat(70));

        String dsl = Files.readString(Path.of("examples/tb_lktn_house.dsl"));
        BuildingDefinition def = BuildingParser.parse(dsl);
        
        Path outputDir = Path.of("output/tb_lktn_verify");
        Files.createDirectories(outputDir);
        
        OutlierLogger.reset();
        BuildingCompiler.BuildingSpec spec = BuildingCompiler.compile(def, outputDir);

        var storey = spec.storeys().get(0);

        // 1. DOOR VERIFICATION
        System.out.println("\n1. DOOR VERIFICATION");
        System.out.println("-".repeat(70));
        System.out.printf("Total doors: %d%n%n", storey.doors().size());
        
        System.out.println("Door details:");
        for (var door : storey.doors()) {
            System.out.printf("  %s: room=%s, wall=%s, pos=(%.2f, %.2f)%n",
                door.name(), door.roomName(), door.wall(),
                door.x(), door.y());
        }
        
        System.out.println("\nDSL DOOR declarations in input:");
        for (var room : def.storeys().get(0).rooms()) {
            for (var opening : room.openings()) {
                if (opening.type().equals("DOOR")) {
                    System.out.printf("  %s \"%s\" has DOOR on %s wall%n",
                        room.type(), room.name(), opening.wall());
                }
            }
        }

        // 2. COLUMN VERIFICATION
        System.out.println("\n2. COLUMN VERIFICATION");
        System.out.println("-".repeat(70));
        System.out.printf("Total columns: %d%n%n", storey.columns().size());
        
        System.out.println("Column details:");
        for (var col : storey.columns()) {
            System.out.printf("  %s: type=%s, pos=(%.2f, %.2f, %.2f)%n",
                col.id(), col.columnType(), col.x(), col.y(), col.z());
        }
        
        System.out.println("\nColumn source: AUTO-GENERATED by StructuralPlacer");
        System.out.println("  - Corner columns at building envelope corners");
        System.out.println("  - T-junction columns where interior walls meet exterior");
        System.out.println("  - NOT from PDF (PDF doesn't show structural elements)");

        // 3. ADJACENCY VERIFICATION
        System.out.println("\n3. ADJACENCY VERIFICATION");
        System.out.println("-".repeat(70));
        
        System.out.println("Room positions (from solver):");
        for (var room : storey.rooms()) {
            System.out.printf("  %s: (%.1f,%.1f) to (%.1f,%.1f) = %.1fm x %.1fm%n",
                room.name(),
                room.minX(), room.minY(), room.maxX(), room.maxY(),
                room.maxX() - room.minX(), room.maxY() - room.minY());
        }
        
        System.out.println("\nShared walls (rooms that touch):");
        var rooms = storey.rooms();
        for (int i = 0; i < rooms.size(); i++) {
            for (int j = i + 1; j < rooms.size(); j++) {
                var r1 = rooms.get(i);
                var r2 = rooms.get(j);
                
                // Check if they share an edge
                boolean shareX = (Math.abs(r1.maxX() - r2.minX()) < 0.01 || 
                                  Math.abs(r2.maxX() - r1.minX()) < 0.01);
                boolean shareY = (Math.abs(r1.maxY() - r2.minY()) < 0.01 || 
                                  Math.abs(r2.maxY() - r1.minY()) < 0.01);
                
                boolean overlapX = r1.minX() < r2.maxX() && r2.minX() < r1.maxX();
                boolean overlapY = r1.minY() < r2.maxY() && r2.minY() < r1.maxY();
                
                if ((shareX && overlapY) || (shareY && overlapX)) {
                    System.out.printf("  %s ↔ %s%n", r1.name(), r2.name());
                }
            }
        }

        // 4. WINDOW VERIFICATION
        System.out.println("\n4. WINDOW VERIFICATION");
        System.out.println("-".repeat(70));
        System.out.printf("Total windows: %d%n%n", storey.windows().size());
        
        System.out.println("Window details:");
        for (var win : storey.windows()) {
            System.out.printf("  %s: room=%s, wall=%s%n",
                win.name(), win.roomName(), win.wall());
        }

        // 5. FIXTURE VERIFICATION
        System.out.println("\n5. FIXTURE VERIFICATION");
        System.out.println("-".repeat(70));
        System.out.printf("Total fixtures: %d%n%n", storey.fixtures().size());
        
        for (var fix : storey.fixtures()) {
            System.out.printf("  %s: room=%s, type=%s%n",
                fix.id(), fix.roomName(), fix.fixtureType());
        }

        // Summary
        System.out.println("\n" + "=".repeat(70));
        System.out.println("VERIFICATION SUMMARY");
        System.out.println("=".repeat(70));
        
        int dslDoorCount = 0;
        for (var room : def.storeys().get(0).rooms()) {
            for (var opening : room.openings()) {
                if (opening.type().equals("DOOR")) dslDoorCount++;
            }
        }
        
        System.out.printf("DSL declares %d doors, compiled %d doors%n", 
            dslDoorCount, storey.doors().size());
        System.out.printf("PDF shows 7+ doors - DSL only has %d (MISSING from DSL)%n", dslDoorCount);
        System.out.println("\nRoot cause: DSL file doesn't declare all doors from PDF!");
        System.out.println("The 3 doors compiled match the 3 DOOR declarations in DSL.");
        System.out.println("PDF doors not in DSL were not extracted to the DSL file.");
    }
}
