package com.bim.designer;

import com.bim.compiler.dsl.PlacementLoader;
import com.bim.designer.api.*;

import org.junit.jupiter.api.*;

import java.io.File;
import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Compile Bridge — wire DesignerAPIImpl.compile() to real CompilationPipeline.
 *
 * <p>Proves that the Designer can invoke the full 9-stage compilation pipeline
 * and produce a real output.db with elements, spatial digest, and geometry.
 *
 * <p>// Implementing BIM_Designer_SRS.md §22 — Witness: W-COMPILE-1..4
 *
 * <p>Prerequisites: library/SH_BOM.db must exist (generated by IFCtoBOM pipeline).
 * Tests are skipped gracefully if it is absent.
 */
@DisplayName("Compile Bridge — Real Pipeline Wire")
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
class CompileBridgeTest {

    private static final String SH_BOM_DB = "library/SH_BOM.db";
    private static final String DSL_FILE = "IFCtoBOM/src/main/resources/dsl_sh.bim";
    private static final String SCHEMA_SQL = "library/schema_snapshot_bom.sql";

    private static Path tempDir;
    private static String compileDbPath;
    private static String outputDir;
    private static DesignerAPIImpl api;
    private static Connection apiConn;

    // Shared across tests — populated by W-COMPILE-1
    private static CompileResponse compileResult;

    @BeforeAll
    static void setUp() throws Exception {
        // Reset singletons to prevent cross-test pollution
        PlacementLoader.resetInstance();

        // Fail visibly if SH_BOM.db or DSL file not available
        assertTrue(new File(SH_BOM_DB).exists(),
                "SH_BOM.db not found — run IFCtoBOM pipeline first");
        assertTrue(new File(DSL_FILE).exists(),
                "dsl_sh.bim not found");

        // Create temp directory for compile DB and output
        tempDir = Files.createTempDirectory("compile_bridge_");
        compileDbPath = tempDir.resolve("_SH_compile.db").toString();
        outputDir = tempDir.resolve("output").toString();
        new File(outputDir).mkdirs();

        // Prepare compile DB: copy SH_BOM.db + add schema + inject C_DocType
        Files.copy(Path.of(SH_BOM_DB), Path.of(compileDbPath));
        prepareCompileDb();

        // Set bom.db BEFORE any pipeline class is loaded — static final fields
        // in CompilationPipeline, MetadataValidator, etc. cache this at class-load time
        System.setProperty("bom.db", compileDbPath);

        // Create API with connection to the compile DB
        apiConn = DriverManager.getConnection("jdbc:sqlite:" + compileDbPath);
        api = new DesignerAPIImpl(apiConn);
    }

    @AfterAll
    static void tearDown() throws Exception {
        if (apiConn != null && !apiConn.isClosed()) apiConn.close();
        // Clear stale bom.db pointer before deleting temp directory
        System.clearProperty("bom.db");
        PlacementLoader.resetInstance();
        // Clean up temp files
        if (tempDir != null) {
            Files.walk(tempDir)
                    .sorted(java.util.Comparator.reverseOrder())
                    .map(Path::toFile)
                    .forEach(File::delete);
        }
    }

    /**
     * Prepare the compile DB following the same steps as run_RosettaStones.sh:
     * 1. Add schema tables from schema_snapshot_bom.sql
     * 2. Read DSL content from dsl_sh.bim
     * 3. Insert C_DocType row with SH parameters
     */
    private static void prepareCompileDb() throws Exception {
        try (Connection conn = DriverManager.getConnection("jdbc:sqlite:" + compileDbPath)) {
            conn.setAutoCommit(false);

            // 1. Add schema tables (IF NOT EXISTS) — same as run_RosettaStones.sh
            if (new File(SCHEMA_SQL).exists()) {
                String schema = Files.readString(Path.of(SCHEMA_SQL));
                // sed-equivalent: CREATE TABLE → CREATE TABLE IF NOT EXISTS
                schema = schema.replace("CREATE TABLE \"", "CREATE TABLE IF NOT EXISTS \"");
                schema = schema.replace("CREATE TABLE M_", "CREATE TABLE IF NOT EXISTS M_");
                schema = schema.replace("CREATE TABLE C_", "CREATE TABLE IF NOT EXISTS C_");
                schema = schema.replace("CREATE TABLE ad_", "CREATE TABLE IF NOT EXISTS ad_");
                schema = schema.replace("CREATE TABLE m_", "CREATE TABLE IF NOT EXISTS m_");
                try (Statement stmt = conn.createStatement()) {
                    for (String ddl : schema.split(";")) {
                        String trimmed = ddl.trim();
                        if (!trimmed.isEmpty()) {
                            try {
                                stmt.execute(trimmed);
                            } catch (Exception ignore) {
                                // Table may already exist or DDL not applicable
                            }
                        }
                    }
                }
            }

            // 2. Read DSL content
            String dslContent = Files.readString(Path.of(DSL_FILE));

            // 3. Read expected elements from ad_sysconfig
            int expectedElements = 58;
            try (Statement stmt = conn.createStatement();
                 var rs = stmt.executeQuery(
                         "SELECT config_value FROM ad_sysconfig WHERE config_key='EXPECTED_ELEMENTS'")) {
                if (rs.next()) expectedElements = rs.getInt(1);
            } catch (Exception ignore) {
                // ad_sysconfig may not exist yet
            }

            // 4. Read AABB from BUILDING BOM
            double aabbW = 0, aabbD = 0, aabbH = 0;
            try (Statement stmt = conn.createStatement();
                 var rs = stmt.executeQuery(
                         "SELECT aabb_width_mm, aabb_depth_mm, aabb_height_mm FROM m_bom WHERE bom_id='BUILDING_SH_STD'")) {
                if (rs.next()) {
                    aabbW = rs.getDouble(1);
                    aabbD = rs.getDouble(2);
                    aabbH = rs.getDouble(3);
                }
            }

            // 5. Ensure C_DocType table exists
            try (Statement stmt = conn.createStatement()) {
                stmt.execute("""
                    CREATE TABLE IF NOT EXISTS C_DocType (
                        C_DocType_ID TEXT PRIMARY KEY,
                        Name TEXT, DocBaseType TEXT, DocSubType TEXT,
                        IsActive INTEGER DEFAULT 1, ProjectName TEXT,
                        OutputDbPath TEXT, ReferenceDbPath TEXT,
                        ExpectedElements INTEGER DEFAULT 0,
                        Provenance TEXT DEFAULT 'EXTRACTED',
                        SeqNo INTEGER DEFAULT 10,
                        DSLContent TEXT,
                        Description TEXT,
                        GeometryFailThreshold INTEGER DEFAULT 0,
                        AabbWidthMm REAL DEFAULT 0,
                        AabbDepthMm REAL DEFAULT 0,
                        AabbHeightMm REAL DEFAULT 0
                    )
                    """);
            }

            // 6. Insert C_DocType row
            String outputPath = outputDir + "/ifc4_samplehouse.db";
            String refPath = "DAGCompiler/lib/input/Ifc4_SampleHouse_extracted.db";
            try (var ps = conn.prepareStatement("""
                    INSERT OR REPLACE INTO C_DocType (
                        C_DocType_ID, Name, DocBaseType, DocSubType, IsActive,
                        ProjectName, OutputDbPath, ReferenceDbPath,
                        ExpectedElements, Provenance, SeqNo, DSLContent,
                        GeometryFailThreshold
                    ) VALUES (?, ?, ?, ?, 1, ?, ?, ?, ?, 'EXTRACTED', 10, ?, 0)
                    """)) {
                ps.setString(1, "RE_SH");
                ps.setString(2, "Sample House");
                ps.setString(3, "RE");
                ps.setString(4, "SH");
                ps.setString(5, "Ifc4_SampleHouse");
                ps.setString(6, outputPath);
                ps.setString(7, refPath);
                ps.setInt(8, expectedElements);
                ps.setString(9, dslContent);
                ps.executeUpdate();
            }

            conn.commit();
        }
    }

    // ── Witness claims (SRS §22.6) ──────────────────────────────────

    @Test
    @Order(1)
    @DisplayName("W-COMPILE-1: compile() with SH_BOM.db produces output.db with 58 elements")
    void w_compile_1_pipeline_produces_elements() {
        CompileRequest request = new CompileRequest(
                "Ifc4_SampleHouse",
                compileDbPath,
                "library/component_library.db",
                outputDir + "/"
        );

        compileResult = api.compile(request);

        assertTrue(compileResult.success(),
                "Compile should succeed: " + compileResult.error());
        assertEquals(58, compileResult.elementCount(),
                "SH produces exactly 58 elements");
    }

    @Test
    @Order(2)
    @DisplayName("W-COMPILE-2: compile() returns outputDbPath that exists on disk")
    void w_compile_2_output_file_exists() {
        assertNotNull(compileResult, "W-COMPILE-1 must run first");
        assertTrue(compileResult.success());

        String outputPath = compileResult.outputDbPath();
        assertNotNull(outputPath, "outputDbPath must not be null");
        assertTrue(new File(outputPath).exists(),
                "Output DB file must exist on disk: " + outputPath);

        // Verify it's a valid SQLite DB with elements_meta
        try (Connection conn = DriverManager.getConnection("jdbc:sqlite:" + outputPath);
             Statement stmt = conn.createStatement();
             var rs = stmt.executeQuery("SELECT COUNT(*) FROM elements_meta")) {
            assertTrue(rs.next());
            assertEquals(58, rs.getInt(1), "Output DB must contain 58 elements");
        } catch (Exception e) {
            fail("Output DB should be a valid SQLite database: " + e.getMessage());
        }
    }

    @Test
    @Order(3)
    @DisplayName("W-COMPILE-3: compile() returns spatialDigest matching G3-DIGEST format (SHA-256)")
    void w_compile_3_spatial_digest_format() {
        assertNotNull(compileResult, "W-COMPILE-1 must run first");
        assertTrue(compileResult.success());

        String digest = compileResult.spatialDigest();
        assertNotNull(digest, "spatialDigest must not be null");
        // SHA-256 = 64 hex characters
        assertTrue(digest.matches("[0-9a-f]{64}"),
                "spatialDigest must be 64 hex chars (SHA-256): got " + digest);
    }

    @Test
    @Order(4)
    @DisplayName("W-COMPILE-4: compile() for SH completes in < 3s (UX-N-09)")
    void w_compile_4_latency_under_3s() {
        assertNotNull(compileResult, "W-COMPILE-1 must run first");
        assertTrue(compileResult.success());

        assertTrue(compileResult.compileTimeMs() < 3000,
                "SH compile should take < 3s, took " + compileResult.compileTimeMs() + "ms");
    }

    @Test
    @Order(5)
    @DisplayName("W-COMPILE-5: compile() with unknown buildingId returns failure")
    void w_compile_5_unknown_building_fails() {
        CompileRequest request = new CompileRequest(
                "NonExistent_Building",
                compileDbPath,
                "library/component_library.db",
                outputDir + "/"
        );

        CompileResponse resp = api.compile(request);
        assertFalse(resp.success(), "Unknown building should fail");
        assertNotNull(resp.error());
    }
}
