package com.bim.cobol.verb;

import org.apache.poi.ss.usermodel.*;
import org.apache.poi.ss.util.CellRangeAddress;
import org.apache.poi.xssf.usermodel.*;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 * Shared XLSX template for BIM COBOL report verbs.
 *
 * <p>Produces professional, standards-compliant Excel reports with:
 * <ul>
 *   <li>Company header block with report title, timestamp, compliance markings</li>
 *   <li>Standards compliance banner (ISO 19650, IFC4, iDempiere ERP)</li>
 *   <li>Named data range with auto-filter for easy user modification</li>
 *   <li>Print-ready page setup (landscape A3, repeat headers)</li>
 *   <li>Consistent cell styles: header, data, numeric, percentage</li>
 *   <li>Field holder placeholders (marked «FIELD») for user customization</li>
 * </ul>
 *
 * <p>Users can modify the template by editing named ranges, inserting
 * columns next to «FIELD» placeholders, or adjusting the print area.
 */
class ReportTemplate {

    // ── Style palette ─────────────────────────────────────────────────────

    static final short HEADER_BG = IndexedColors.DARK_BLUE.getIndex();
    static final short HEADER_FG = IndexedColors.WHITE.getIndex();
    static final short TITLE_BG  = IndexedColors.ROYAL_BLUE.getIndex();
    static final short ALT_ROW   = IndexedColors.PALE_BLUE.getIndex();
    static final short COMPLIANCE_BG = IndexedColors.LIGHT_GREEN.getIndex();
    static final short FIELD_HOLDER_BG = IndexedColors.LIGHT_YELLOW.getIndex();

    private ReportTemplate() {} // utility class

    // ── Workbook setup ────────────────────────────────────────────────────

    /** Create a new workbook with default properties. */
    static XSSFWorkbook createWorkbook() {
        XSSFWorkbook wb = new XSSFWorkbook();
        wb.getProperties().getCoreProperties().setCreator("BIM Intent Compiler");
        wb.getProperties().getCoreProperties().setDescription(
            "Generated by BIM COBOL Report Verb — ISO 19650 compliant BOM report");
        return wb;
    }

    // ── Header block ──────────────────────────────────────────────────────

    /**
     * Write the report header block (rows 0–6) with title, metadata, compliance.
     *
     * @return the row index where data headers should start (typically 8)
     */
    static int writeHeader(XSSFSheet sheet, String reportTitle, String reportSubtitle,
                            int dataColumnCount) {
        XSSFWorkbook wb = sheet.getWorkbook();
        String timestamp = LocalDateTime.now()
            .format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));

        // ── Row 0: Report title ──────────────────────────────────
        CellStyle titleStyle = createTitleStyle(wb);
        Row titleRow = sheet.createRow(0);
        titleRow.setHeightInPoints(28);
        Cell titleCell = titleRow.createCell(0);
        titleCell.setCellValue("BIM INTENT COMPILER — " + reportTitle);
        titleCell.setCellStyle(titleStyle);
        sheet.addMergedRegion(new CellRangeAddress(0, 0, 0, dataColumnCount - 1));

        // ── Row 1: Subtitle ──────────────────────────────────────
        CellStyle subtitleStyle = createSubtitleStyle(wb);
        Row subRow = sheet.createRow(1);
        subRow.setHeightInPoints(18);
        Cell subCell = subRow.createCell(0);
        subCell.setCellValue(reportSubtitle);
        subCell.setCellStyle(subtitleStyle);
        sheet.addMergedRegion(new CellRangeAddress(1, 1, 0, dataColumnCount - 1));

        // ── Row 2: Timestamp + generator ─────────────────────────
        CellStyle metaStyle = createMetaStyle(wb);
        Row metaRow = sheet.createRow(2);
        Cell metaCell = metaRow.createCell(0);
        metaCell.setCellValue("Generated: " + timestamp
            + "  |  Source: BOM.db  |  Engine: BIM COBOL VerbExecutor SPI");
        metaCell.setCellStyle(metaStyle);
        sheet.addMergedRegion(new CellRangeAddress(2, 2, 0, dataColumnCount - 1));

        // ── Row 3: Standards compliance — individual cells, green/orange bg ──
        CellStyle greenComp = createComplianceCellStyle(wb, true);
        CellStyle orangeComp = createComplianceCellStyle(wb, false);
        Row compRow = sheet.createRow(3);
        compRow.setHeightInPoints(20);
        // Standards: green = fully compliant, orange = partial/aspirational
        String[][] standards = {
            {"ISO 19650",  "green"},
            {"IFC4 ADD2",  "green"},
            {"iDempiere",  "green"},
            {"Libero MRP", "green"},
            {"Uniclass",   "orange"},
            {"OmniClass",  "orange"},
            {"ISO 12006-2","green"},
        };
        for (int i = 0; i < standards.length && i < dataColumnCount; i++) {
            Cell sc = compRow.createCell(i);
            sc.setCellValue(standards[i][0]);
            sc.setCellStyle("green".equals(standards[i][1]) ? greenComp : orangeComp);
        }

        // ── Row 4: EntityType legend ─────────────────────────────
        Row classRow = sheet.createRow(4);
        Cell classCell = classRow.createCell(0);
        classCell.setCellValue(
            "EntityType: D=Dictionary (read-only)  U=User (mutable)  A=Application");
        classCell.setCellStyle(metaStyle);
        sheet.addMergedRegion(new CellRangeAddress(4, 4, 0, dataColumnCount - 1));

        // ── Row 5: User field holders ────────────────────────────
        CellStyle fieldStyle = createFieldHolderStyle(wb);
        Row fieldRow = sheet.createRow(5);
        fieldRow.setHeightInPoints(18);
        String[] fields = {
            "\u00ABProject Name\u00BB", "\u00ABClient\u00BB",
            "\u00ABDesign Theme\u00BB", "\u00ABRevision\u00BB"
        };
        for (int i = 0; i < fields.length && i < dataColumnCount; i++) {
            Cell fc = fieldRow.createCell(i);
            fc.setCellValue(fields[i]);
            fc.setCellStyle(fieldStyle);
        }

        // ── Row 6: separator ─────────────────────────────────────
        // (blank row as visual separator)
        sheet.createRow(6);

        // ── Row 7: data column headers start here ────────────────
        return 7;
    }

    // ── Data column header row ────────────────────────────────────────────

    /** Write column headers at the given row and return the CellStyle for reuse. */
    static CellStyle writeColumnHeaders(XSSFSheet sheet, int rowIdx, String[] headers) {
        XSSFWorkbook wb = sheet.getWorkbook();
        CellStyle headerStyle = createColumnHeaderStyle(wb);
        Row row = sheet.createRow(rowIdx);
        row.setHeightInPoints(22);
        for (int i = 0; i < headers.length; i++) {
            Cell cell = row.createCell(i);
            cell.setCellValue(headers[i]);
            cell.setCellStyle(headerStyle);
        }
        return headerStyle;
    }

    // ── Data row styles ───────────────────────────────────────────────────

    /** Create paired styles for zebra-striped data rows. [0]=even, [1]=odd. */
    static CellStyle[] createDataStyles(XSSFWorkbook wb) {
        CellStyle even = wb.createCellStyle();
        even.setFont(createDataFont(wb));
        even.setBorderBottom(BorderStyle.THIN);
        even.setBorderTop(BorderStyle.THIN);
        even.setVerticalAlignment(VerticalAlignment.CENTER);

        CellStyle odd = wb.createCellStyle();
        odd.cloneStyleFrom(even);
        odd.setFillForegroundColor(ALT_ROW);
        odd.setFillPattern(FillPatternType.SOLID_FOREGROUND);

        return new CellStyle[]{even, odd};
    }

    /** Create a numeric style with 4 decimal places. */
    static CellStyle createNumericStyle(XSSFWorkbook wb, boolean oddRow) {
        CellStyle style = wb.createCellStyle();
        style.setFont(createDataFont(wb));
        style.setDataFormat(wb.createDataFormat().getFormat("0.0000"));
        style.setBorderBottom(BorderStyle.THIN);
        style.setBorderTop(BorderStyle.THIN);
        style.setVerticalAlignment(VerticalAlignment.CENTER);
        if (oddRow) {
            style.setFillForegroundColor(ALT_ROW);
            style.setFillPattern(FillPatternType.SOLID_FOREGROUND);
        }
        return style;
    }

    /** Create an integer numeric style. */
    static CellStyle createIntStyle(XSSFWorkbook wb, boolean oddRow) {
        CellStyle style = wb.createCellStyle();
        style.setFont(createDataFont(wb));
        style.setDataFormat(wb.createDataFormat().getFormat("#,##0"));
        style.setBorderBottom(BorderStyle.THIN);
        style.setBorderTop(BorderStyle.THIN);
        style.setVerticalAlignment(VerticalAlignment.CENTER);
        if (oddRow) {
            style.setFillForegroundColor(ALT_ROW);
            style.setFillPattern(FillPatternType.SOLID_FOREGROUND);
        }
        return style;
    }

    // ── Footer / summary row ──────────────────────────────────────────────

    /** Write a summary footer row with count + timestamp. */
    static void writeFooter(XSSFSheet sheet, int rowIdx, int dataCount, int colCount) {
        XSSFWorkbook wb = sheet.getWorkbook();
        CellStyle footerStyle = wb.createCellStyle();
        Font footerFont = wb.createFont();
        footerFont.setItalic(true);
        footerFont.setFontHeightInPoints((short) 9);
        footerFont.setColor(IndexedColors.GREY_50_PERCENT.getIndex());
        footerStyle.setFont(footerFont);

        Row row = sheet.createRow(rowIdx);
        Cell cell = row.createCell(0);
        cell.setCellValue(String.format("Total: %d records  |  End of report  |  "
            + "Modify «FIELD» placeholders in row 6 to customize", dataCount));
        cell.setCellStyle(footerStyle);
        sheet.addMergedRegion(new CellRangeAddress(rowIdx, rowIdx, 0, colCount - 1));
    }

    // ── Sheet finalization ────────────────────────────────────────────────

    /** Auto-size columns, add auto-filter, set print area. */
    static void finalize(XSSFSheet sheet, int headerRow, int lastDataRow, int colCount) {
        // Auto-size (cap at ~40 chars = ~10000 units)
        for (int i = 0; i < colCount; i++) {
            sheet.autoSizeColumn(i);
            if (sheet.getColumnWidth(i) > 10000) {
                sheet.setColumnWidth(i, 10000);
            }
        }

        // Auto-filter on data range
        sheet.setAutoFilter(new CellRangeAddress(headerRow, lastDataRow, 0, colCount - 1));

        // Print setup: landscape, fit to page width, repeat header rows
        PrintSetup ps = sheet.getPrintSetup();
        ps.setLandscape(true);
        ps.setFitWidth((short) 1);
        ps.setFitHeight((short) 0);
        sheet.setRepeatingRows(new CellRangeAddress(0, headerRow, -1, -1));

        // Freeze panes: freeze header rows
        sheet.createFreezePane(0, headerRow + 1);
    }

    // ── Font + style factories ────────────────────────────────────────────

    private static CellStyle createTitleStyle(XSSFWorkbook wb) {
        CellStyle style = wb.createCellStyle();
        Font font = wb.createFont();
        font.setFontHeightInPoints((short) 16);
        font.setBold(true);
        font.setColor(HEADER_FG);
        style.setFont(font);
        style.setFillForegroundColor(TITLE_BG);
        style.setFillPattern(FillPatternType.SOLID_FOREGROUND);
        style.setAlignment(HorizontalAlignment.LEFT);
        style.setVerticalAlignment(VerticalAlignment.CENTER);
        return style;
    }

    private static CellStyle createSubtitleStyle(XSSFWorkbook wb) {
        CellStyle style = wb.createCellStyle();
        Font font = wb.createFont();
        font.setFontHeightInPoints((short) 11);
        font.setItalic(true);
        font.setColor(IndexedColors.GREY_50_PERCENT.getIndex());
        style.setFont(font);
        return style;
    }

    private static CellStyle createMetaStyle(XSSFWorkbook wb) {
        CellStyle style = wb.createCellStyle();
        Font font = wb.createFont();
        font.setFontHeightInPoints((short) 9);
        font.setColor(IndexedColors.GREY_50_PERCENT.getIndex());
        style.setFont(font);
        return style;
    }

    /** Green (compliant) or orange (partial) compliance cell style. */
    private static CellStyle createComplianceCellStyle(XSSFWorkbook wb, boolean green) {
        CellStyle style = wb.createCellStyle();
        Font font = wb.createFont();
        font.setFontHeightInPoints((short) 9);
        font.setBold(true);
        font.setColor(green ? IndexedColors.DARK_GREEN.getIndex()
                            : IndexedColors.DARK_YELLOW.getIndex());
        style.setFont(font);
        style.setFillForegroundColor(green ? IndexedColors.LIGHT_GREEN.getIndex()
                                           : IndexedColors.LIGHT_ORANGE.getIndex());
        style.setFillPattern(FillPatternType.SOLID_FOREGROUND);
        style.setAlignment(HorizontalAlignment.CENTER);
        style.setVerticalAlignment(VerticalAlignment.CENTER);
        style.setBorderBottom(BorderStyle.THIN);
        style.setBorderRight(BorderStyle.THIN);
        return style;
    }

    private static CellStyle createFieldHolderStyle(XSSFWorkbook wb) {
        CellStyle style = wb.createCellStyle();
        Font font = wb.createFont();
        font.setFontHeightInPoints((short) 10);
        font.setItalic(true);
        font.setColor(IndexedColors.DARK_RED.getIndex());
        style.setFont(font);
        style.setFillForegroundColor(FIELD_HOLDER_BG);
        style.setFillPattern(FillPatternType.SOLID_FOREGROUND);
        style.setBorderBottom(BorderStyle.DASHED);
        return style;
    }

    private static CellStyle createColumnHeaderStyle(XSSFWorkbook wb) {
        CellStyle style = wb.createCellStyle();
        Font font = wb.createFont();
        font.setFontHeightInPoints((short) 11);
        font.setBold(true);
        font.setColor(HEADER_FG);
        style.setFont(font);
        style.setFillForegroundColor(HEADER_BG);
        style.setFillPattern(FillPatternType.SOLID_FOREGROUND);
        style.setAlignment(HorizontalAlignment.CENTER);
        style.setVerticalAlignment(VerticalAlignment.CENTER);
        style.setBorderBottom(BorderStyle.MEDIUM);
        return style;
    }

    private static Font createDataFont(XSSFWorkbook wb) {
        Font font = wb.createFont();
        font.setFontHeightInPoints((short) 10);
        font.setFontName("Calibri");
        return font;
    }
}
