package com.bim.designer;

import com.bim.designer.api.DesignerAPI;
import com.bim.designer.api.DesignerAPIImpl;

import org.junit.jupiter.api.*;

import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Verb Dispatch — proves Designer executeVerb() wires to VerbRegistry.
 *
 * <p>// Implementing BBC.md §6 — Witness: W-VERB-DISPATCH-1
 *
 * <p>Prerequisites: library/SH_BOM.db must exist (generated by IFCtoBOM pipeline).
 */
@DisplayName("Verb Dispatch — Designer ↔ VerbRegistry Wire")
class VerbDispatchTest {

    private static final String SH_BOM_DB = "library/SH_BOM.db";

    private static Connection bomConn;
    private static DesignerAPIImpl api;

    @BeforeAll
    static void setUp() throws Exception {
        assertTrue(new File(SH_BOM_DB).exists(),
                "SH_BOM.db not found — run IFCtoBOM pipeline first");

        bomConn = DriverManager.getConnection("jdbc:sqlite:" + SH_BOM_DB);
        api = new DesignerAPIImpl(bomConn);
    }

    @AfterAll
    static void tearDown() throws Exception {
        if (bomConn != null && !bomConn.isClosed()) bomConn.close();
    }

    /**
     * W-VERB-DISPATCH-1: Designer can dispatch a verb to VerbRegistry.
     * executeVerb(CHECK BOM) routes through VerbRegistry.dispatch(), not the stub.
     * @Traces BBC.md §6 — verb dispatch is not stubbed
     */
    @Test
    @DisplayName("W-VERB-DISPATCH-1: executeVerb(CHECK BOM) dispatches to VerbRegistry")
    void verbDispatchFromDesigner() {
        // CHECK BOM BUILDING_SH_STD — real dispatch returns verb="CHECK BOM"
        // and a real summary (BOM walk results), not "Stub execution of..."
        DesignerAPI.VerbResponse resp = api.executeVerb("SH", "CHECK BOM BUILDING_SH_STD");

        assertEquals("CHECK BOM", resp.verb(),
                "Verb keyword should be CHECK BOM (from VerbRegistry, not stub)");
        assertNotNull(resp.summary(), "Summary should not be null");
        // Summary from real dispatch contains BOM stats, not "Stub execution"
        assertFalse(resp.summary().contains("Stub"),
                "Response must come from VerbRegistry, not the old stub");
    }

    /**
     * W-VERB-DISPATCH-2: Unknown verb returns structured failure, not exception.
     * @Traces BBC.md §6 — VerbRegistry handles unknown keywords gracefully
     */
    @Test
    @DisplayName("W-VERB-DISPATCH-2: unknown verb returns failure response")
    void unknownVerbReturnsFailure() {
        DesignerAPI.VerbResponse resp = api.executeVerb("SH", "XYZZY PLUGH");

        assertFalse(resp.success(), "Unknown verb should not succeed");
        assertNotNull(resp.error(), "Error message should explain the failure");
    }
}
