#!/bin/bash
# export_ad.sh — Export iDempiere AD metadata + GardenWorld data to SQLite
# Source: docker postgres container with idempiere DB
# Output: deploy/dev/ad_seed.sql
# Usage: bash scripts/export_ad.sh
#
# Exports:
#   1. AD metadata tables (AD_Menu, AD_Window, AD_Tab, AD_Field, AD_Column, etc.)
#   2. GardenWorld client data (C_BPartner, M_Product, C_Project, etc.)
#   3. System reference data (AD_Ref_List, AD_Reference, AD_Element)
#
# Copyright (c) 2025-2026 Redhuan D. Oon. MIT Licensed.

set -e

CONTAINER=postgres
DB=idempiere
USER=adempiere
OUTPUT=deploy/dev/ad_seed.sql
TMPDIR=/tmp/ad_export

echo "§EXPORT starting iDempiere AD export..."
echo "§EXPORT container=$CONTAINER db=$DB output=$OUTPUT"

# Ensure postgres is running
docker start $CONTAINER >/dev/null 2>&1 || true
sleep 1

# Verify connection
docker exec $CONTAINER psql -U $USER -d $DB -c "SELECT 1" >/dev/null 2>&1 || {
    echo "§EXPORT ERROR: cannot connect to $CONTAINER/$DB"; exit 1;
}

mkdir -p $TMPDIR
rm -f $TMPDIR/*.csv

# ── Function: export a table with selected columns ────────────────────

export_table() {
    local TABLE=$1
    local COLUMNS=$2
    local WHERE=${3:-"1=1"}
    local OUTFILE=$TMPDIR/${TABLE}.csv

    echo "§EXPORT exporting $TABLE WHERE $WHERE ..."
    docker exec $CONTAINER psql -U $USER -d $DB \
        -c "COPY (SELECT $COLUMNS FROM $TABLE WHERE $WHERE AND IsActive='Y') TO STDOUT WITH (FORMAT csv, HEADER true, NULL '')" \
        > "$OUTFILE" 2>/dev/null

    local COUNT=$(wc -l < "$OUTFILE")
    COUNT=$((COUNT - 1))  # subtract header
    echo "§EXPORT $TABLE rows=$COUNT"
}

# ── Export AD metadata tables ─────────────────────────────────────────

export_table "AD_Menu" \
    "AD_Menu_ID, Name, Description, IsSummary, Action, AD_Window_ID, AD_Process_ID, AD_Form_ID, IsActive"

export_table "AD_TreeNodeMM" \
    "AD_Tree_ID, Node_ID, Parent_ID, SeqNo, IsActive" \
    "AD_Tree_ID = 10"

export_table "AD_Window" \
    "AD_Window_ID, Name, Description, Help, WindowType, IsActive"

export_table "AD_Tab" \
    "AD_Tab_ID, AD_Window_ID, Name, Description, Help, AD_Table_ID, TabLevel, SeqNo, IsSingleRow, IsReadOnly, WhereClause, OrderByClause, IsActive"

export_table "AD_Field" \
    "AD_Field_ID, AD_Tab_ID, AD_Column_ID, Name, Description, Help, SeqNo, IsDisplayed, DisplayLogic, IsMandatory, IsReadOnly, DefaultValue, IsActive"

export_table "AD_Column" \
    "AD_Column_ID, AD_Table_ID, ColumnName, Name, Description, AD_Reference_ID, AD_Val_Rule_ID, FieldLength, IsMandatory, IsKey, IsIdentifier, DefaultValue, ValueMin, ValueMax, IsActive"

export_table "AD_Table" \
    "AD_Table_ID, TableName, Name, Description, AD_Window_ID, IsActive"

export_table "AD_Reference" \
    "AD_Reference_ID, Name, Description, ValidationType, IsActive"

export_table "AD_Ref_List" \
    "AD_Ref_List_ID, AD_Reference_ID, Value, Name, Description, IsActive"

export_table "AD_Element" \
    "AD_Element_ID, ColumnName, Name, PrintName, Description, IsActive"

# ── Export GardenWorld data tables (AD_Client_ID = 11) ────────────────

echo ""
echo "§EXPORT exporting GardenWorld data (AD_Client_ID=11)..."

export_table "C_BPartner" \
    "C_BPartner_ID, AD_Client_ID, AD_Org_ID, Value, Name, Name2, Description, IsCustomer, IsVendor, IsEmployee, C_BP_Group_ID, IsActive" \
    "AD_Client_ID = 11"

export_table "C_BPartner_Location" \
    "C_BPartner_Location_ID, AD_Client_ID, C_BPartner_ID, Name, Phone, Fax, IsActive" \
    "AD_Client_ID = 11"

export_table "AD_User" \
    "AD_User_ID, AD_Client_ID, AD_Org_ID, Name, Description, EMail, Phone, C_BPartner_ID, IsActive" \
    "AD_Client_ID IN (0, 11)"

export_table "M_Product" \
    "M_Product_ID, AD_Client_ID, AD_Org_ID, Value, Name, Description, M_Product_Category_ID, ProductType, C_UOM_ID, IsActive" \
    "AD_Client_ID = 11"

export_table "M_Product_Category" \
    "M_Product_Category_ID, AD_Client_ID, Name, Description, Value, IsActive" \
    "AD_Client_ID = 11"

export_table "M_ProductPrice" \
    "M_Product_ID, M_PriceList_Version_ID, PriceList, PriceStd, PriceLimit, IsActive" \
    "AD_Client_ID = 11"

export_table "C_Project" \
    "C_Project_ID, AD_Client_ID, AD_Org_ID, Value, Name, Description, C_BPartner_ID, DateContract, DateFinish, PlannedAmt, CommittedAmt, DocStatus, IsActive" \
    "AD_Client_ID = 11"

# ── Convert CSV to SQLite INSERTs ─────────────────────────────────────

echo ""
echo "§EXPORT converting CSV to SQLite INSERTs..."

python3 -c "
import csv, os, sys, glob

outfile = '$OUTPUT'
tmpdir = '$TMPDIR'

with open(outfile, 'w') as out:
    out.write('-- ad_seed.sql — iDempiere AD metadata + GardenWorld data\n')
    out.write('-- Auto-generated by scripts/export_ad.sh\n')
    out.write('-- Source: docker postgres / idempiere DB\n')
    out.write('-- Copyright (c) 2025-2026 Redhuan D. Oon. MIT Licensed.\n\n')

    # Schema DDL first
    schemas = {
        'AD_Menu': 'CREATE TABLE IF NOT EXISTS AD_Menu (AD_Menu_ID INTEGER PRIMARY KEY, Name TEXT NOT NULL, Description TEXT, IsSummary TEXT DEFAULT \"N\", Action TEXT, AD_Window_ID INTEGER, AD_Process_ID INTEGER, AD_Form_ID INTEGER, IsActive TEXT DEFAULT \"Y\")',
        'AD_TreeNodeMM': 'CREATE TABLE IF NOT EXISTS AD_TreeNodeMM (AD_Tree_ID INTEGER NOT NULL, Node_ID INTEGER NOT NULL, Parent_ID INTEGER NOT NULL, SeqNo INTEGER DEFAULT 0, IsActive TEXT DEFAULT \"Y\", PRIMARY KEY (AD_Tree_ID, Node_ID))',
        'AD_Window': 'CREATE TABLE IF NOT EXISTS AD_Window (AD_Window_ID INTEGER PRIMARY KEY, Name TEXT NOT NULL, Description TEXT, Help TEXT, WindowType TEXT DEFAULT \"M\", IsActive TEXT DEFAULT \"Y\")',
        'AD_Tab': 'CREATE TABLE IF NOT EXISTS AD_Tab (AD_Tab_ID INTEGER PRIMARY KEY, AD_Window_ID INTEGER NOT NULL, Name TEXT NOT NULL, Description TEXT, Help TEXT, AD_Table_ID INTEGER NOT NULL, TabLevel INTEGER DEFAULT 0, SeqNo INTEGER DEFAULT 10, IsSingleRow TEXT DEFAULT \"N\", IsReadOnly TEXT DEFAULT \"N\", WhereClause TEXT, OrderByClause TEXT, IsActive TEXT DEFAULT \"Y\")',
        'AD_Field': 'CREATE TABLE IF NOT EXISTS AD_Field (AD_Field_ID INTEGER PRIMARY KEY, AD_Tab_ID INTEGER NOT NULL, AD_Column_ID INTEGER NOT NULL, Name TEXT NOT NULL, Description TEXT, Help TEXT, SeqNo INTEGER DEFAULT 10, IsDisplayed TEXT DEFAULT \"Y\", DisplayLogic TEXT, IsMandatory TEXT, IsReadOnly TEXT DEFAULT \"N\", DefaultValue TEXT, IsActive TEXT DEFAULT \"Y\")',
        'AD_Column': 'CREATE TABLE IF NOT EXISTS AD_Column (AD_Column_ID INTEGER PRIMARY KEY, AD_Table_ID INTEGER NOT NULL, ColumnName TEXT NOT NULL, Name TEXT, Description TEXT, AD_Reference_ID INTEGER, AD_Val_Rule_ID INTEGER, FieldLength INTEGER DEFAULT 0, IsMandatory TEXT DEFAULT \"N\", IsKey TEXT DEFAULT \"N\", IsIdentifier TEXT DEFAULT \"N\", DefaultValue TEXT, ValueMin TEXT, ValueMax TEXT, IsActive TEXT DEFAULT \"Y\")',
        'AD_Table': 'CREATE TABLE IF NOT EXISTS AD_Table (AD_Table_ID INTEGER PRIMARY KEY, TableName TEXT NOT NULL, Name TEXT, Description TEXT, AD_Window_ID INTEGER, IsActive TEXT DEFAULT \"Y\")',
        'AD_Reference': 'CREATE TABLE IF NOT EXISTS AD_Reference (AD_Reference_ID INTEGER PRIMARY KEY, Name TEXT NOT NULL, Description TEXT, ValidationType TEXT, IsActive TEXT DEFAULT \"Y\")',
        'AD_Ref_List': 'CREATE TABLE IF NOT EXISTS AD_Ref_List (AD_Ref_List_ID INTEGER PRIMARY KEY, AD_Reference_ID INTEGER NOT NULL, Value TEXT NOT NULL, Name TEXT NOT NULL, Description TEXT, IsActive TEXT DEFAULT \"Y\")',
        'AD_Element': 'CREATE TABLE IF NOT EXISTS AD_Element (AD_Element_ID INTEGER PRIMARY KEY, ColumnName TEXT, Name TEXT NOT NULL, PrintName TEXT, Description TEXT, IsActive TEXT DEFAULT \"Y\")',
        'C_BPartner': 'CREATE TABLE IF NOT EXISTS C_BPartner (C_BPartner_ID INTEGER PRIMARY KEY, AD_Client_ID INTEGER, AD_Org_ID INTEGER, Value TEXT, Name TEXT NOT NULL, Name2 TEXT, Description TEXT, IsCustomer TEXT DEFAULT \"N\", IsVendor TEXT DEFAULT \"N\", IsEmployee TEXT DEFAULT \"N\", C_BP_Group_ID INTEGER, IsActive TEXT DEFAULT \"Y\")',
        'C_BPartner_Location': 'CREATE TABLE IF NOT EXISTS C_BPartner_Location (C_BPartner_Location_ID INTEGER PRIMARY KEY, AD_Client_ID INTEGER, C_BPartner_ID INTEGER, Name TEXT, Phone TEXT, Fax TEXT, IsActive TEXT DEFAULT \"Y\")',
        'AD_User': 'CREATE TABLE IF NOT EXISTS AD_User (AD_User_ID INTEGER PRIMARY KEY, AD_Client_ID INTEGER, AD_Org_ID INTEGER, Name TEXT NOT NULL, Description TEXT, EMail TEXT, Phone TEXT, C_BPartner_ID INTEGER, IsActive TEXT DEFAULT \"Y\")',
        'M_Product': 'CREATE TABLE IF NOT EXISTS M_Product (M_Product_ID INTEGER PRIMARY KEY, AD_Client_ID INTEGER, AD_Org_ID INTEGER, Value TEXT, Name TEXT NOT NULL, Description TEXT, M_Product_Category_ID INTEGER, ProductType TEXT, C_UOM_ID INTEGER, IsActive TEXT DEFAULT \"Y\")',
        'M_Product_Category': 'CREATE TABLE IF NOT EXISTS M_Product_Category (M_Product_Category_ID INTEGER PRIMARY KEY, AD_Client_ID INTEGER, Name TEXT NOT NULL, Description TEXT, Value TEXT, IsActive TEXT DEFAULT \"Y\")',
        'M_ProductPrice': 'CREATE TABLE IF NOT EXISTS M_ProductPrice (M_Product_ID INTEGER NOT NULL, M_PriceList_Version_ID INTEGER NOT NULL, PriceList REAL, PriceStd REAL, PriceLimit REAL, IsActive TEXT DEFAULT \"Y\", PRIMARY KEY (M_Product_ID, M_PriceList_Version_ID))',
        'C_Project': 'CREATE TABLE IF NOT EXISTS C_Project (C_Project_ID INTEGER PRIMARY KEY, AD_Client_ID INTEGER, AD_Org_ID INTEGER, Value TEXT, Name TEXT NOT NULL, Description TEXT, C_BPartner_ID INTEGER, DateContract TEXT, DateFinish TEXT, PlannedAmt REAL, CommittedAmt REAL, DocStatus TEXT DEFAULT \"DR\", IsActive TEXT DEFAULT \"Y\")',
    }

    out.write('-- §SCHEMA DDL\\n')
    for tbl, ddl in schemas.items():
        out.write(ddl + ';\\n')
    out.write('\\n')

    total_rows = 0
    for csvfile in sorted(glob.glob(os.path.join(tmpdir, '*.csv'))):
        tbl = os.path.splitext(os.path.basename(csvfile))[0]
        with open(csvfile, 'r') as f:
            reader = csv.reader(f)
            headers = next(reader)
            rows = list(reader)

        if not rows:
            continue

        out.write(f'-- §SEED_{tbl} rows={len(rows)}\\n')
        for row in rows:
            vals = []
            for v in row:
                if v == '' or v is None:
                    vals.append('NULL')
                else:
                    try:
                        # Try integer
                        int(v)
                        vals.append(v)
                    except ValueError:
                        try:
                            float(v)
                            vals.append(v)
                        except ValueError:
                            vals.append(\"'\" + v.replace(\"'\", \"''\") + \"'\")
            cols = ', '.join(headers)
            valstr = ', '.join(vals)
            out.write(f'INSERT OR IGNORE INTO {tbl} ({cols}) VALUES ({valstr});\\n')
        out.write('\\n')
        total_rows += len(rows)
        print(f'  {tbl}: {len(rows)} rows')

    print(f'\\nTotal: {total_rows} rows written to {outfile}')
"

# ── Verify ────────────────────────────────────────────────────────────

LINECOUNT=$(wc -l < "$OUTPUT")
FILESIZE=$(du -h "$OUTPUT" | cut -f1)
echo ""
echo "§EXPORT done output=$OUTPUT lines=$LINECOUNT size=$FILESIZE"
echo "§EXPORT verify: load in sqlite3 and count tables"
