#!/usr/bin/env python3
"""
Emit a Modeller self-heal SQL patch carrying a building's rel_fills_host edges.

WHY THIS EXISTS
---------------
`sdg_cascade.js stretchRide()` — the thing that makes a hosted door/window RIDE its wall during a
Grid-Stretch instead of warping — is guarded on `window.swXEdges.fills` (bonsai_gridmove.js:249), which
reads the `rel_fills_host` table (cross_edges.js:251). Every shipped `modeller/*_ARC.db` predates
extractIFCtoDB.py's `extract_rel_fills_host()`, so the table is simply absent and the cascade silently
no-ops. Measured 2026-07-27: 0 of 6 residents carried it. `docs/ModellerGuide.md` documents the ride as
shipped behaviour, so the honest fix is to SHIP THE RELATION, not to soften the sentence.

Per the project DB-change policy the delivery is a SQL patch + the existing self-heal loader
(`str_walker_outliner.js _applyPendingPatch`, convention `modeller/patches/<dbFile>.sql`) — never a
rebuilt binary crossing the network.

NON-INVENT: the edges are recovered verbatim from the source IFC's own IfcRelVoidsElement /
IfcRelFillsElement by extractIFCtoDB.py's own `extract_rel_fills_host()` — this script imports that
function rather than reimplementing it, so there is exactly one recovery implementation. Nothing is
derived, clustered, or proximity-guessed.

Usage:
  python3 scripts/gen_rel_fills_host_patch.py --ifc <source.ifc> --target <path/to/X_ARC.db> \
      --out <path/to/modeller/patches/X_ARC.db.sql>
"""
import argparse
import datetime
import os
import sqlite3
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                                "DAGCompiler", "python"))

DDL = """CREATE TABLE IF NOT EXISTS rel_fills_host (
    opening_guid TEXT PRIMARY KEY,
    host_guid TEXT,
    filling_guid TEXT,
    host_class TEXT,
    filling_class TEXT,
    provenance TEXT DEFAULT 'ifc:recovered'
);"""


def sql_quote(v):
    return "NULL" if v is None else "'" + str(v).replace("'", "''") + "'"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--ifc", required=True, help="source IFC the ARC db was extracted from")
    ap.add_argument("--target", required=True, help="the shipped modeller/<X>_ARC.db this patch applies to")
    ap.add_argument("--out", required=True, help="output .sql path")
    args = ap.parse_args()

    import ifcopenshell
    from extractIFCtoDB import extract_rel_fills_host

    ifc = ifcopenshell.open(args.ifc)
    mem = sqlite3.connect(":memory:")
    mem.execute(DDL)
    rows, filled = extract_rel_fills_host(ifc, mem)
    data = mem.execute("SELECT opening_guid, host_guid, filling_guid, host_class, filling_class "
                       "FROM rel_fills_host ORDER BY opening_guid").fetchall()
    if not data:
        print(f"  §RFH-PATCH {os.path.basename(args.ifc)}: 0 void/fill relations in the source IFC — "
              f"nothing to ship (this building's author never declared any). No file written.")
        return 1

    # Measure, against the REAL target, how much of this is actually reachable — the guide must not
    # promise a ride the scene cannot perform. A host or filling with no element_instances row is not a
    # scene feature, so fidByGuid[] is null for it and stretchRide skips that edge.
    tgt = sqlite3.connect("file:" + args.target + "?mode=ro", uri=True)

    def rendered(g):
        return g is not None and tgt.execute(
            "SELECT 1 FROM element_instances WHERE guid=?", (g,)).fetchone() is not None

    rideable = sum(1 for r in data if r[2] and rendered(r[1]) and rendered(r[2]))
    dbfile = os.path.basename(args.target)

    out = [
        f"-- {dbfile} rel_fills_host — the authored host<->opening<->filling chain (§PATHB).",
        "-- Self-heal patch. Generated by scripts/gen_rel_fills_host_patch.py (bim-compiler) — regenerate,",
        "-- do not hand-edit. Recovery is extractIFCtoDB.py extract_rel_fills_host(), the ONE implementation.",
        "--",
        f"-- Source: {os.path.basename(args.ifc)}   Generated: {datetime.date.today().isoformat()}",
        f"-- Recovered VERBATIM from the source IFC's own IfcRelVoidsElement/IfcRelFillsElement:",
        f"--   {rows} host edges, {filled} with a door/window filling, {rows - filled} open voids.",
        "-- provenance='ifc:recovered' on every row. Nothing derived, nothing proximity-guessed.",
        "--",
        "-- WHY: sdg_cascade.js stretchRide() is guarded on window.swXEdges.fills (bonsai_gridmove.js:249)",
        "-- which reads this table (cross_edges.js:251). Without it a hosted door/window does NOT ride its",
        "-- wall on a Grid-Stretch — the cascade silently no-ops. docs/ModellerGuide.md documents the ride.",
        "--",
        f"-- MEASURED REACH on this exact target: {rideable}/{filled} fills have BOTH ends present as scene",
        "-- features (a host with no element_instances row never becomes a feature, so that edge is skipped).",
        "--",
        "-- Idempotent: CREATE IF NOT EXISTS + INSERT OR IGNORE on the opening_guid PRIMARY KEY, so the",
        "-- loader re-applying it on every open is a no-op.",
        DDL,
    ]
    for r in data:
        out.append(
            "INSERT OR IGNORE INTO rel_fills_host "
            "(opening_guid,host_guid,filling_guid,host_class,filling_class,provenance) VALUES ("
            + ",".join(sql_quote(x) for x in r) + ",'ifc:recovered');")

    os.makedirs(os.path.dirname(os.path.abspath(args.out)), exist_ok=True)
    with open(args.out, "w") as fh:
        fh.write("\n".join(out) + "\n")
    print(f"  §RFH-PATCH {dbfile}: {rows} edges ({filled} filled), rideable={rideable}/{filled} → {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
