package com.bim.designer.api;

import com.bim.compiler.dsl.VerbExecutor;
import com.bim.designer.api.DesignerAPI;
import com.bim.designer.api.DesignerAPIImpl;

import org.junit.jupiter.api.*;

import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Verb Emission — proves Designer emitVerbs() wires to VerbExecutor SPI.
 *
 * <p>// Implementing BBC.md §6 — GUI emits BIM COBOL verbs, never direct SQL
 * <p>// Implementing BIM_Designer_SRS.md §33 — Verb Emission Protocol
 *
 * <p>Prerequisites: library/SH_BOM.db must exist (generated by IFCtoBOM pipeline).
 */
@DisplayName("Verb Emission — Designer GUI → VerbExecutor Pipeline")
class VerbEmissionTest {

    private static final String SH_BOM_DB = "library/SH_BOM.db";

    private static Connection bomConn;
    private static DesignerAPIImpl api;

    @BeforeAll
    static void setUp() throws Exception {
        assertTrue(new File(SH_BOM_DB).exists(),
                "SH_BOM.db not found — run IFCtoBOM pipeline first");

        bomConn = DriverManager.getConnection("jdbc:sqlite:" + SH_BOM_DB);
        api = new DesignerAPIImpl(bomConn);
    }

    @AfterAll
    static void tearDown() throws Exception {
        if (bomConn != null && !bomConn.isClosed()) bomConn.close();
    }

    /**
     * W-EMIT-1: emitVerbs() dispatches verb lines via VerbExecutor SPI.
     * A valid LIST BOM verb fires through the SPI and returns a report.
     * @Traces BIM_Designer_SRS.md §33 — Verb Emission Protocol
     */
    @Test
    @DisplayName("W-EMIT-1: emitVerbs dispatches via VerbExecutor SPI")
    void emitVerbsDispatchesViaSPI() {
        // SELECT BOM always succeeds when the BOM exists in SH_BOM.db
        VerbExecutor.ExecutionReport report =
                api.emitVerbs("SH", List.of("SELECT BOM BUILDING_SH_STD"));

        assertNotNull(report, "Report must not be null");
        assertTrue(report.passCount() > 0, "At least one verb should pass");
        assertEquals(0, report.failCount(), "No verbs should fail");
        assertFalse(report.details().isEmpty(), "Details must contain verb summaries");
    }

    /**
     * W-EMIT-2: ExecutionReport returns accurate pass/fail counts for a batch.
     * @Traces BIM_Designer_SRS.md §33.4 — Interface Contract
     */
    @Test
    @DisplayName("W-EMIT-2: batch emission returns correct counts")
    void batchEmissionReturnsCorrectCounts() {
        VerbExecutor.ExecutionReport report = api.emitVerbs("SH", List.of(
                "SELECT BOM BUILDING_SH_STD",
                "DESCRIBE BOM BUILDING_SH_STD"
        ));

        assertNotNull(report);
        assertEquals(2, report.passCount() + report.failCount(),
                "Total should equal number of verb lines");
        assertEquals(2, report.details().size(),
                "One detail line per verb");
    }

    /**
     * W-EMIT-3: Unknown verb in batch returns failCount > 0, does not throw.
     * @Traces BIM_Designer_SRS.md §33.5 — Error handling
     */
    @Test
    @DisplayName("W-EMIT-3: unknown verb fails gracefully, no exception")
    void unknownVerbFailsGracefully() {
        VerbExecutor.ExecutionReport report = api.emitVerbs("SH", List.of(
                "XYZZY PLUGH"
        ));

        assertNotNull(report, "Report must not be null even for unknown verbs");
        assertTrue(report.failCount() > 0, "Unknown verb should produce a failure");
        assertEquals(0, report.passCount(), "No verbs should pass");
    }

    /**
     * W-EMIT-4: Empty verb list returns zero counts, no exception.
     * @Traces BIM_Designer_SRS.md §33.5 — Rules
     */
    @Test
    @DisplayName("W-EMIT-4: empty verb list returns zero report")
    void emptyVerbListReturnsZeroReport() {
        VerbExecutor.ExecutionReport report = api.emitVerbs("SH", List.of());

        assertNotNull(report);
        assertEquals(0, report.passCount());
        assertEquals(0, report.failCount());
        assertTrue(report.details().isEmpty());
    }
}
